{
 "title": "TPLink EasySmartSwitch Stats - PLUS",
 "tags": [
  "tplink",
  "switch",
  "networking"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "host",
    "query": "label_values(tplinkexporter_portstats_state, host)"
   }
  ]
 },
 "panels": [
  {
   "title": "Port Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tplinkexporter_portstats_state{host=\"$host\"}",
     "legendFormat": "Port {{portnum}}"
    }
   ]
  },
  {
   "title": "Port Link Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tplinkexporter_portstats_linkstatus{host=\"$host\"}",
     "legendFormat": "Port {{portnum}}"
    }
   ]
  },
  {
   "title": "Port Configuration Overview",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "tplinkexporter_portconfig_info{host=\"$host\"}",
     "legendFormat": "Port {{portnum}} - {{speed_actual}} ({{state}})"
    }
   ]
  },
  {
   "title": "System Information",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "tplinkexporter_system_info{host=\"$host\"}",
     "legendFormat": "{{device_description}} - FW: {{firmware_version}} - HW: {{hardware_version}}"
    }
   ]
  },
  {
   "title": "Port Link Status Over Time",
   "type": "graph",
   "description": "6 = 1000MF\n5 = 100MF\n4 = 100MH\n3 = 10MF\n2 = 10MH\n1 = Auto\n0 = Link Down",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tplinkexporter_portstats_linkstatus{host=\"$host\"} !=0",
     "legendFormat": "Port {{portnum}}"
    }
   ]
  },
  {
   "title": "Good Packet Rates (packets/sec)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(tplinkexporter_portstats_rxgoodpkt{host=\"$host\"}[10s])",
     "legendFormat": "RX Port {{portnum}}"
    },
    {
     "expr": "rate(tplinkexporter_portstats_txgoodpkt{host=\"$host\"}[10s])",
     "legendFormat": "TX Port {{portnum}}"
    }
   ]
  },
  {
   "title": "Bad Packet Rates (packets/sec)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(tplinkexporter_portstats_rxbadpkt{host=\"$host\"}[10s])",
     "legendFormat": "RX Port {{portnum}}"
    },
    {
     "expr": "rate(tplinkexporter_portstats_txbadpkt{host=\"$host\"}[10s])",
     "legendFormat": "TX Port {{portnum}}"
    }
   ]
  }
 ]
}