name: Build Container

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build container image
      run: |
        docker build -t ${{ gitea.repository }}:${{ gitea.sha }} .
        docker build -t ${{ gitea.repository }}:latest .